fix: end points
6RiverSystems/light_scan_sim pull request #4
Opened 2019-08-21 19:52 UTC by dnikitop

2019-08-22 18:55 UTC, DrCodeWizzard approved these changes

2019-09-05 15:46 UTC, grieneis approved these changes

2019-09-12 20:32 UTC, grieneis requested changes
UPdate comment

2019-09-12 20:32 UTC, grieneis commented on test/test_ray_cast.cpp
> +  EXPECT_NEAR(s.ranges[2], 50.0, 1e-5);  // max range + 1m for no return
The comment no longer seems valid.

2019-09-25 18:17 UTC, grieneis approved these changes

2019-10-01 17:18 UTC, merged